### PR TITLE
Tidy FileStream implementation

### PR DESCRIPTION
**Pull request by tmpfs**

### CODE REVIEW

**Comment by tmpfs** [comment]
I would be tempted to remove `OpenType` completely and let the caller configure the file how they want and then just wrap it in a `FileStream`, what do you think?

**Comment by tmpfs** [comment]
Ok, so that `OpenType` enum always felt a bit clunky to me, so here is a version that deletes it and I think exposes a more idiomatic API.

**Comment by mathias234** [comment]
We could leave the old way also that way we dont need a major version bump. But it probably doesnt matter

**Comment by tmpfs** [comment]
Sure i understand if you want to keep it as is; I just think that the current API of passing an `OpenType` and having `FileStream` do the file opening is not very intuitive or idiomatic. There are also occasions where you may want to do something with the file first before passing it off to the `FileStream`.

**Comment by mathias234** [comment]
> Sure i understand if you want to keep it as is; I just think that the current API of passing an `OpenType` and having `FileStream` do the file opening is not very intuitive or idiomatic. There are also occasions where you may want to do something with the file first before passing it off to the `FileStream`.

Well, I like your approach, my idea was to keep both of them, so the user can either do
new(path, OpenType)
read(path)
write(path)

**Comment by tmpfs** [comment]
Oh i see, you want to keep it backward compatible. My motivation for the PR was to simplify the API surface a little and remove `OpenType` as I often find myself forgetting that I need it and it's just another thing to import when really I would prefer just to do `FileStream(File::open(path)?)` so maybe best to just ignore this if you like the existing API 👍 If it were up to me I wouldn't event provide the convenience methods as people are likely very familiar with the `std::fs::File` API.

**Comment by mathias234** [comment]
After some consideration, I think i agree with this implementation, thank you :)

**Pull request merged**
