### PR TITLE
Added 7bit encoded integer, String size changed to use 7bit

### PR DESCRIPTION
**Pull request by rusticpow**
Applied clippy suggestions.

The fixes to get closer to dotnet implementation of BinaryReader/Writer

### CODE REVIEW

**Comment by mathias234** [comment]
This would be a breaking change for any previously written strings. I wonder if it might be worth doing it as a feature flag, similar to how wasm was changed to using i32 sizes instead of usize

**Comment by rusticpow** [comment]
Agree. But might be separate functions are better for 7bit encoding?

**Comment by mathias234** [comment]
Separate functions also work for me

**Comment by rusticpow** [comment]
Put into functions. 
Am I right that because of usize, the implementation is not suitable to de/serialize in different machines, so it cant' be used for network? 
Is it okay if I add configuration where u32/u64 is a length instead of usize?

**Comment by mathias234** [comment]
> Put into functions. Am I right that because of usize, the implementation is not suitable to de/serialize in different machines, so it cant' be used for network? Is it okay if I add configuration where u32/u64 is a length instead of usize?

Yes, this is correct, usize will be the length of a memory address. I wasn't aware of this when I initially made this library, I think making it configurable is a good idea :slightly_smiling_face:

**Comment by mathias234** [comment]
Merging this now, feel free to do the usize to u32/u64 configuration in a separate PR

**Pull request merged**
