### PR TITLE
Optional serde implementation

### PR DESCRIPTION
**Pull request by tmpfs**
Feature gated using the `serde` feature.

Currently supports primitive values; requires work to handle all the complex types like sequences, structs, enums, tuples etc.

### CODE REVIEW

**Comment by tmpfs** [comment]
Not sure if this interests you @mathias234 but I think it would be really useful to be able to implement `Serialize` and `Deserialize` when designing file formats.

**Comment by mathias234** [comment]
Hmm, I am not quite sure I see the benefits of this, over just using serde. Are you thinking about mixing manual writing/reading with automatic serialization/deserialization? 

I originally wrote this because I wanted to write file formats that did not match the in memory structure. Although I can possibly see the benefit of being able to mix it.

**Comment by tmpfs** [comment]
At the moment I am doing the encoding / decoding ad-hoc using these traits (which we could probably fold into this crate):

```rust
use crate::Result;
use binary_rw::{BinaryReader, BinaryWriter};

/// Trait for encoding to binary.
pub trait Encode {
    /// Encode self into the binary writer.
    fn encode(&self, writer: &mut BinaryWriter) -> Result<()>;
}

/// Trait for decoding from binary.
pub trait Decode {
    /// Decode from the binary reader into self.
    fn decode(&mut self, reader: &mut BinaryReader) -> Result<()>;
}
```

But I am following the structure of the data in memory so it feels like quite a bit of work updating the encoding / decoding routines whenever I need to change the data structure(s).

An ideal solution would be to mix serde with overrides using those traits, as you mention, but I am not sure if this is possible or how we might achieve it.

If you don't think this is something to explore in the context of this crate it would be quite straightforward for me to put this in another crate, `serde-binary` maybe?

**Comment by tmpfs** [comment]
So these latest commits add more or less full support for serde, if I have missed some types I will fix later.

This also includes support for the reading and writing the `char` type so if we move this to another crate then I can cherry pick those changes to `BinaryReader` and `BinaryWriter`.

I played with `downcast` a little and I don't think it will work as downcasting to a trait requires boxing and the `'static` lifetime; so I think it is realistically an "either or" situation.

So I suggest that we:

* Add support for the `char` type
* Fold the `Encode` and `Decode` traits into this crate
* Move this serde support to the `serde-binary` crate

Does that work for you @mathias234?

**Comment by mathias234** [comment]
@tmpfs I think what you suggest here works moving the serde parts to its own crate, as I feel it's not quite in the scope of what this crate is. I am fine with adding the Encode and Decode traits and the char type :slightly_smiling_face:

**Comment by tmpfs** [comment]
Cool, I have moved the code here: https://github.com/tmpfs/serde-binary.

I think I know how we can get the best of both worlds actually. Because the `Serializer` and `Deserializer` wrap the `BinaryWriter` and `BinaryReader` I can create new traits that expose the `Serializer` and `Deserializer` (lets call them `Encodable` and `Decodable` not to conlict with the lower-level `Encode` and `Decode` traits) then implementations can either use the `Serializer` / `Deserializer` or the wrapped `BinaryWriter` and `BinaryReader`. Provided the encoding and decoding are symmetrical it should work fine.

**Pull request closed without merging**
